
#################################################
### THIS FILE WAS AUTOGENERATED! DO NOT EDIT! ###
#################################################
# file to edit: Q2.ipynb

import csv
import numpy as np  # http://www.numpy.org
import ast
from datetime import datetime
from math import log, floor, ceil
import random
import numpy as np

class Utility(object):

    # This method computes entropy for information gain
    def entropy(self, class_y):
        # Input:
        #   class_y         : list of class labels (0's and 1's)

        # TODO: Compute the entropy for a list of classes
        #
        # Example:
        x = [0,0,0,1,1,1,1,1,1] #= 0.918 (rounded to three decimal places)

        entropy = 0
        ### Implement your code here
        #############################################

        #H = – SUM_OF_ALL_THE_EVENTS(the probability of the event * log2(the probability of the event).
        #print(class_y)

        n_labels = len(class_y)

        if n_labels <= 1:
            #print("RETURNED 0")
            return 0

        counts = np.bincount(class_y)
        probs = counts / n_labels
        n_classes = np.count_nonzero(probs)

        if n_classes <= 1:
            return 0

        ent = 0.

        # Compute standard entropy.
        #print("PROBS: ", probs)
        for i in probs:
            if(i!=0):
                ent -= i * log(i, 2)
            else:
                ent-=0

        #print(ent)


        entropy = ent
        #############################################
        return entropy


    def partition_classes(self, X , y, split_attribute=0, split_val=3):
        X_left = []
        X_right = []

        y_left = []
        y_right = []



#         X = [[3, 10],
#              [1, 22],
#              [2, 28],
#              [5, 32],
#              [4, 32]]
#         y = [1, 1, 0, 0, 1]

#         split_attribute = 0
#         split_val = 3

        for row in X:
            if row[split_attribute] <= split_val:
                X_left.append(row)
                y_left.append(y[X.index(row)])
            else:
                X_right.append(row)
                y_right.append(y[X.index(row)])

#         print(X_left)
#         print(X_right)
#         print(y_left)
#         print(y_right)

        # Inputs:
        #   X               : data containing all attributes
        #   y               : labels
        #   split_attribute : column index of the attribute to split on
        #   split_val       : a numerical value to divide the split_attribute



        # TODO: Partition the data(X) and labels(y) based on the split value - BINARY SPLIT.
        #
        # Split_val should be a numerical value
        # For example, your split_val could be the mean of the values of split_attribute
        #
        # You can perform the partition in the following way
        # Numeric Split Attribute:
        #   Split the data X into two lists(X_left and X_right) where the first list has all
        #   the rows where the split attribute is less than or equal to the split value, and the
        #   second list has all the rows where the split attribute is greater than the split
        #   value. Also create two lists(y_left and y_right) with the corresponding y labels.



        '''
        Example:



        X = [[3, 10],                 y = [1,
             [1, 22],                      1,
             [2, 28],                      0,
             [5, 32],                      0,
             [4, 32]]                      1]



        Here, columns 0 and 1 represent numeric attributes.



        Consider the case where we call the function with split_attribute = 0 and split_val = 3 (mean of column 0)
        Then we divide X into two lists - X_left, where column 0 is <= 3  and X_right, where column 0 is > 3.



        X_left = [[3, 10],                 y_left = [1,
                  [1, 22],                           1,
                  [2, 28]]                           0]



        X_right = [[5, 32],                y_right = [0,
                   [4, 32]]                           1]



        '''


        ### Implement your code here
        #############################################

        pass
        #############################################
        return (X_left, X_right, y_left, y_right)


    def information_gain(self, previous_y, current_y):
        # Inputs:
        #   previous_y: the distribution of original labels (0's and 1's)
        #   current_y:  the distribution of labels after splitting based on a particular
        #               split attribute and split value

        # TODO: Compute and return the information gain from partitioning the previous_y labels
        # into the current_y labels.
        # You will need to use the entropy function above to compute information gain
        # Reference: http://www.cs.cmu.edu/afs/cs.cmu.edu/academic/class/15381-s06/www/DTs.pdf

        """
        Example:

        previous_y = [0,0,0,1,1,1]
        current_y = [[0,0], [1,1,1,0]]

        info_gain = 0.45915
        """
        #print("INSIDE INFO GAIN")
        #previous_y = [0,0,0,1,1,1]
        total_n = len(previous_y)
        #current_y = [[0,0], [1,1,1,0]]
        old_entropy = self.entropy(previous_y)
        #print("OLD ENTROPY: ", old_entropy)
        new_entropies = []
        new_probs = []
        n_labels = 2
        for y in current_y:
            #print("Y: ", y)
            ent = self.entropy(y)
            new_entropies.append(ent)
            new_probs.append(len(y)/total_n)
            counts = np.bincount(y)
            probs = counts / n_labels
            #print("Probs: ", new_probs)
        #print("OLD ENTROPY: ", old_entropy)
        #print("NEW ENTROPIES: ", new_entropies)
        info_gain = 0
        for n_ent in new_entropies:
            info_gain += new_probs[new_entropies.index(n_ent)]*n_ent
        info_gain = old_entropy-info_gain
        ### Implement your code here
        #############################################

        #print("INFO GAIN: ", info_gain)
        #############################################
        return info_gain


    def best_split(self, X, y):
        # Inputs:
        #   X       : Data containing all attributes
        #   y       : labels
        #   TODO    : For each node find the best split criteria and return the split attribute,
        #             spliting value along with  X_left, X_right, y_left, y_right (using partition_classes)
        #             in the dictionary format {'split_attribute':split_attribute, 'split_val':split_val,
        #             'X_left':X_left, 'X_right':X_right, 'y_left':y_left, 'y_right':y_right, 'info_gain':info_gain}
        '''

        Example:

        X = [[3, 10],                 y = [1,
             [1, 22],                      1,
             [2, 28],                      0,
             [5, 32],                      0,
             [4, 32]]                      1]

        Starting entropy: 0.971

        Calculate information gain at splits: (In this example, we are testing all values in an
        attribute as a potential split value, but you can experiment with different values in your implementation)

        feature 0:  -->    split_val = 1  -->  info_gain = 0.17
                           split_val = 2  -->  info_gain = 0.01997
                           split_val = 3  -->  info_gain = 0.01997
                           split_val = 4  -->  info_gain = 0.32
                           split_val = 5  -->  info_gain = 0

                           best info_gain = 0.32, best split_val = 4


        feature 1:  -->    split_val = 10  -->  info_gain = 0.17
                           split_val = 22  -->  info_gain = 0.41997
                           split_val = 28  -->  info_gain = 0.01997
                           split_val = 32  -->  info_gain = 0

                           best info_gain = 0.4199, best split_val = 22


       best_split_feature: 1
       best_split_val: 22

       'X_left': [[3, 10], [1, 22]]
       'X_right': [[2, 28],[5, 32], [4, 32]]

       'y_left': [1, 1]
       'y_right': [0, 0, 1]
        '''
#         X = [[3, 10],
#              [1, 22],
#              [2, 28],
#              [5, 32],
#              [4, 32]]
#         y = [1, 1, 0, 0, 1]
#         entropy = 0.971
        ent_dict = {}
        total_feat = len(X[0])
        split_attribute = 0
        split_val = 0
        X_left, X_right, y_left, y_right = [], [], [], []

        for i in range(total_feat):
            ent_dict[i] = {}

        for i in range(total_feat):
            for j in range(50):
                X_left, X_right, y_left, y_right = self.partition_classes(X, y, i, j)
                new_y = [y_left, y_right]

                ent_dict[i][j] = self.information_gain(y, new_y)

        #print("ENT_DICT: ", ent_dict)

        max_key_list = []
        max_value_list = []
        for d in ent_dict:
            max_key = max(ent_dict[d], key=ent_dict[d].get)
            max_key_list.append(max_key)
            max_value_list.append(ent_dict[d][max_key])

        max_value = max(max_value_list)
        max_feat = max_value_list.index(max_value)
        split_val = max_key_list[max_feat]

        X_left, X_right, y_left, y_right = self.partition_classes(X, y, max_feat, split_val)

        return_dict = {'split_attribute':max_feat, 'split_val':split_val, 'X_left':X_left, 'X_right':X_right, 'y_left':y_left, 'y_right':y_right, 'info_gain':max_value}

        #print("RETURN DICT: ", return_dict)
        return return_dict


        ### Implement your code here
        #############################################

        pass
        #############################################

# This starter code does not run. You will have to add your changes and
# turn in code that runs properly.

"""
Here,
1. X is assumed to be a matrix with n rows and d columns where n is the
number of total records and d is the number of features of each record.
2. y is assumed to be a vector of labels of length n.
3. XX is similar to X, except that XX also contains the data label for each
record.
"""

"""
This skeleton is provided to help you implement the assignment.You must
implement the existing functions as necessary. You may add new functions
as long as they are called from within the given classes.

VERY IMPORTANT!
Do NOT change the signature of the given functions.
Do NOT change any part of the main function APART from the forest_size parameter.
"""


class RandomForest(object):
    num_trees = 0
    decision_trees = []

    # the bootstrapping datasets for trees
    # bootstraps_datasets is a list of lists, where each list in bootstraps_datasets is a bootstrapped dataset.
    bootstraps_datasets = []

    # the true class labels, corresponding to records in the bootstrapping datasets
    # bootstraps_labels is a list of lists, where the 'i'th list contains the labels corresponding to records in
    # the 'i'th bootstrapped dataset.
    bootstraps_labels = []

    def __init__(self, num_trees):
        # Initialization done here
        self.num_trees = 10
        self.decision_trees = [DecisionTree(max_depth=num_trees) for i in range(num_trees)]
        self.bootstraps_datasets = []
        self.bootstraps_labels = []

    def _bootstrapping(self, XX, n):
        # Reference: https://en.wikipedia.org/wiki/Bootstrapping_(statistics)
        #
        # TODO: Create a sample dataset of size n by sampling with replacement
        #       from the original dataset XX.
        # Note that you would also need to record the corresponding class labels
        # for the sampled records for training purposes.

        sample = []  # sampled dataset
        labels = []  # class labels for the sampled records
        ### Implement your code here
        #############################################
        # print("XX: ", XX)
        # print("n: ", n)

        random_index = np.random.choice(len(XX), n, replace=True)
        for i in random_index:
            sample.append(XX[i][:-1])
            labels.append(XX[i][-1])
        #############################################
        return (sample, labels)

    def bootstrapping(self, XX):
        # Initializing the bootstap datasets for each tree
        for i in range(self.num_trees):
            data_sample, data_label = self._bootstrapping(XX, len(XX))
            self.bootstraps_datasets.append(data_sample)
            self.bootstraps_labels.append(data_label)

    def fitting(self):
        # TODO: Train `num_trees` decision trees using the bootstraps datasets
        # and labels by calling the learn function from your DecisionTree class.
        ### Implement your code here
        #############################################
        for i in range(self.num_trees):
            self.decision_trees[i].learn(self.bootstraps_datasets[i], self.bootstraps_labels[i])

        #############################################

    def voting(self, X):
        y = []

        for record in X:
            # Following steps have been performed here:
            #   1. Find the set of trees that consider the record as an
            #      out-of-bag sample.
            #   2. Predict the label using each of the above found trees.
            #   3. Use majority vote to find the final label for this recod.
            votes = []

            for i in range(len(self.bootstraps_datasets)):
                dataset = self.bootstraps_datasets[i]

                if record not in dataset:
                    OOB_tree = self.decision_trees[i]
                    effective_vote = OOB_tree.classify(record)
                    votes.append(effective_vote)

            print("VOTES: ", votes)

            counts = np.bincount(votes)

            if len(counts) == 0:
                # TODO: Special case
                #  Handle the case where the record is not an out-of-bag sample
                #  for any of the trees.
                # NOTE - you can add few lines of codes above (but inside voting) to make this work
                ### Implement your code here
                #############################################
                index = -1
                for i in range(len(self.bootstraps_datasets)):
                    index = self.bootstraps_datasets[i].index(record)
                    if index != -1:
                        y = np.append(y, self.bootstraps_labels[i][index])
                        break
                pass
                #############################################
            else:
                y = np.append(y, np.argmax(counts))

        return y

    def user(self):
        """
        :return: string
        your GTUsername, NOT your 9-Digit GTId
        """
        ### Implement your code here
        #############################################
        return 'gburdell3'
        #############################################


# TODO: Determine the forest size according to your implementation.
# This function will be used by the autograder to set your forest size during testing
# VERY IMPORTANT: Minimum forest_size should be 10
def get_forest_size():
    forest_size = 10
    return forest_size

# TODO: Determine random seed to set for reproducibility
# This function will be used by the autograder to set the random seed to obtain the same results you achieve locally
def get_random_seed():
    random_seed = 0
    return random_seed